//Forensics outline from Textbook0 Google Doc on shared picoCTF drive
//  The Worlds of Forensics
//    As a Profession
//    As a Capture-The-Flag Competition Category
//  Leading an Investigation
//    The Intuitive Leap
//    Courage with Small Leads
//    Relating Disparate Evidence
//    Getting Unstuck by Phoning a Friend
//  The Knowledge of Digital Structures
//    Bits, Nibbles, Bytes, Words, Double Words, Quad Words
//    Hardware of Storage Mediums (Hard Drives, Disks, etc.)
//    Software of Storage Systems (Filesystems, Memory Management, etc.)
//    Protocols of Communication Systems (TCP & other packet analysis)
//  Tools, Techniques & Procedures of Adversaries
//    Destruction of Hardware
//    Timestamp Manipulation
//    File Deletion
//    Hiding Files
//    Steganography

== Forensics

=== What is Forensics?

In general, computer science professionals refer to "Digital Forensics" as
"Forensics", for simplicity's sake. Digital Forensics is the field in
cybersecurity that tries to gather and understand evidence after an incident,
which can be crime, to determine how it happened. This not only helps law
enforcement when pledging someone innocent or guilty, but also to understand
how to improve security in a system that was successfully attacked. Digital
Forensics focuses on gathering evidence present in computer devices that hold
information electronically. It is a branch of Forensic Science, which can also
investigate any type of crime even if there is not computer media involved. 

=== How to search for strings and filenames

We will begin by learning how to search for information in a file system. Go
to the picoCTF webshell at:

https://webshell.picoctf.org/

Once you are connected, open up this problem in a separate tab:

https://play.picoctf.org/practice/challenge/85

Download the problem file in your webshell by right-clicking the link in the
problem description and selecting Copy Address or Copy Link. Then download it
by typing in `wget ` and pasting the address after 'wget', space. Your command
should look something like this, but is likely to not be exactly the same:

[source, text]
$ wget https://jupiter.challenges.picoctf.org/static/495d43ee4a2b9f345a4307d053b4d88d/file

You need to copy and paste your own link for the file.

Great! So now you should have the challenge file saved on your webshell as
`file`. Now what?

As a reflex, you should always use the program `file` on new files that CTF
challenges give you. The next command is kind of confusing, because the first
word references the program `file` and the second word references the file
named `file`, but run this command and see what it tells you:

[source, text]
$ file file

If done properly, it should tell you:

[source, text]
file: ASCII text, with very long lines

This tells us the file is plain text, but has unusually long lines. Since it
is plain text, we can use `cat` to see what it contains.

[source, text]
$ cat file

Running this command will show that the file is mostly made up of gibberish.
If this were a cryptography challenge, decoding the gibberish might be what
needs to happen, but this is a 100 point general skills question, so I doubt
that's what needs to happen here. What is the challenge author pushing us
towards? There's only one hint and it is a `grep` tutorial. What is grep?

Grep is a Linux utility, so we can learn about it by bringing up its man page:

[source, text]
$ man grep

The first line of the man page says:

[source, text]
grep, egrep, fgrep, rgrep - print lines that match patterns

This is perfect! We want to search through gibberish to find the flag. But how
do we specify the pattern to search for and the file to search in? For this,
I recommend the grep tutorial in the hint, not the man page. (Man pages tend
to be highly technical and can be confusing to novices)

One of the first examples in the grep tutorial uses the following command:

[source, text]
$ egrep 'mellon' mysampledata.txt

'mellon' is what is being searched for and it is being searched for in
'mysampledata.txt' What if we searched for 'picoCTF' in 'file'? That command
would look like:

[source, text]
$ egrep 'picoCTF' file

This should get the flag for you and print it on your screen.

Let's consider another challenge:

--challenge link here--
