//Forensics outline from Textbook0 Google Doc on shared picoCTF drive
//  The Worlds of Forensics
//    As a Profession
//    As a Capture-The-Flag Competition Category
//  Leading an Investigation
//    The Intuitive Leap
//    Courage with Small Leads
//    Relating Disparate Evidence
//    Getting Unstuck by Phoning a Friend
//  The Knowledge of Digital Structures
//    Bits, Nibbles, Bytes, Words, Double Words, Quad Words
//    Hardware of Storage Mediums (Hard Drives, Disks, etc.)
//    Software of Storage Systems (Filesystems, Memory Management, etc.)
//    Protocols of Communication Systems (TCP & other packet analysis)
//  Tools, Techniques & Procedures of Adversaries
//    Destruction of Hardware
//    Timestamp Manipulation
//    File Deletion
//    Hiding Files
//    Steganography

== Forensics

When people work in the computer science field they generally call “Forensics”, for shorter, to “Digital Forensics”, which is the field in cybersecurity that tries to gather and understand evidence after an incident, which can be crime, to determine how it happened. This not only helps law enforcement when pledging someone innocent or guilty, but also to understand how to improve security in a system that was successfully attacked. Digital Forensics focuses on gathering evidence present in computer devices that can hold information electronically. It is a branch of Forensic Science, which can also investigate any type of crime to gather evidence and understand how it happened. 

We will begin by learning how to search for information in a file system.  y. Go to the shell server in its web version at:
https://2019game.picoctf.com/https://2019game.picoctf.com/]
Or use ssh to connect to it:
ssh your_username@2019shell1.picoctf.com

Once you are connected, download the file files.zip from the following url:
https://primer.picoctf.com/files/files.zip

To do that, run:
[source, txt]
wget https://primer.picoctf.com/files/files.zip
That will download the .zip file, which is a compressed folder, to your current folder. To uncompress it, run:
[source, txt]
unzip files.zip
You will obtain a folder called files in your current directory. Let’s try a little challenge. That folder has a  lot of files and folders. More than 8000 files. Try to find the following string there:
[source, txt]
information on the record will last a billion years. Genes and brains and books
You know by now that you can access folders using the command ‘cd’. For example, to access the folder ‘files’ that you just uncompressed, you can run:

[source, txt]
cd files

But in more than 8000 files, it is very hard to find one string to exploring the files manually. We have computers to help us with that. 
You could run:

[source, txt]
grep -r "information on the record will last a billion years. Genes and brains and books"

Note that grep is a program in linux intended for searching strings in files. The ‘-r’ in the command, is use to tell grep that It should search insides any folder inside the current folder. When you run it, you will see something like this:
grep -r "information on the record will last a billion years. Genes and brains and books"
folder_pmbymkjcya/folder_cawigcwvgv/folder_ltdayfmktr/folder_fnpfclfyee/whzxrpivpqld.txt:information on the record will last a billion years. Genes and brains and books encode
Not that the string you wanted was found. It shows you the path of the file. In this case, is:

[source, txt]
folder_pmbymkjcya/folder_cawigcwvgv/folder_ltdayfmktr/folder_fnpfclfyee/whzxrpivpqld.txt

We can see that even if we have a huge amount of files, a computer can find something very quickly. Now, suppose we know the name of the file, and we want to know the path. Suppose you want to find the file called ‘file_klcvdqhi.txt’
You can run:
find . -name file_klcvdqhi.txt


As a output, you should see the path:

[source, txt]
./folder_aziwuihrzs/folder_noitiuqyjv/file_klcvdqhi.txt

That was rather simple, but let’s dive into more interesting challenges! 
